#pragma once

#include <QApplication>
#include <QCheckBox>
#include <QClipboard>
#include <QColorDialog>
#include <QComboBox>
#include <QDateEdit>
#include <QDebug>
#include <QDoubleSpinBox>
#include <QFileDialog>
#include <QFontDialog>
#include <QGraphicsPixmapItem>
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QKeyEvent>
#include <QLineEdit>
#include <QMenu>
#include <QMessageBox>
#include <QMetaProperty>
#include <QPainter>
#include <QPixmap>
#include <QScrollBar>
#include <QTextEdit>
#include <QTreeWidgetItem>
#include <QVBoxLayout>

#include <HelperLibrary/Resources/resourceexplorerdialog.h>
#include <HelperLibrary/Styles/iconsenum.h>
#include <HelperLibrary/Widgets/VariantMapEditor/VariantMapEditor.h>
#include <HelperLibrary/Widgets/dialogwrapper.h>
#include <HelperLibrary/Widgets/widgethelper.h>
#include <HelperLibrary/functions.h>
#include <HelperLibrary/releaseassert.h>
